'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
function fn(n){const start=html.search(new RegExp('(?:async )?function '+n+'\\('));assert(start>=0,n);let d=0;for(let i=html.indexOf('{',start);i<html.length;i++){if(html[i]==='{')d++;if(html[i]==='}'&&--d===0)return html.slice(start,i+1);}throw Error(n);}
function setup(store=new Map()){const nodes=new Map(),shown=new Set(),deleted=[],messages=[];let center={lat:0,lng:0};
 const layer=(lat=0,lng=0)=>{const l={addTo(){shown.add(l);return l;},getBounds:()=>({isValid:()=>true,getCenter:()=>({lat,lng})}),getLayers:()=>[{}]};return l;};
 const e={console,sbUser:{id:'A'},_LOCAL_KML_KEY:'local',_KML_USER_STYLES_KEY:'style',kmlLs:[],_kmlEditIdx:-1,_locFotos:[],_sharedFotos:[],_tacke:[],textLabels:[],_msrRegistry:[],_msrSavedLayer:null,_tragRegistry:[],_tragLayers:{},_tragHitLayers:{},_tragLenMk:{},_projekti:[],_aktivniProjektId:'P',
 localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(e.quota)throw Error('quota');store.set(k,v);}},
 document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',hidden:false,style:{display:'none'}});return nodes.get(id);}},
 map:{getCenter:()=>center,distance(a,b){b=Array.isArray(b)?{lat:b[0],lng:b[1]}:b;return Math.hypot(a.lat-b.lat,a.lng-b.lng)*1000;},hasLayer:l=>shown.has(l),removeLayer:l=>shown.delete(l),closePopup(){},on(){},setView(p){center={lat:p[0],lng:p[1]};}},
 _escHtml:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),_kmlFeatureCount:()=>1,_tragIme:t=>t.name,_tragFmtLen:n=>Math.round(n)+' m',_tragCalcLen:p=>p.length*100,_layerEditorHtml:()=>'',
 _tragRegAddLayer(t){for(const x of [e._tragLayers[t.id],e._tragHitLayers[t.id],e._tragLenMk[t.id]])if(x){t.visible?shown.add(x):shown.delete(x);}},_tragRegSave:()=>true,_tragoviRender(){},_kmlcDelete:async k=>deleted.push(k),rndGraniceModal(){},_rndOznakePanel(){},_dlgConfirm:async()=>true,showToast:m=>messages.push(m)};
 e.window=e;vm.createContext(e);vm.runInContext(['saveKmlStyles','_localKmlSaveAll','_kmlSaveTag','delK'].map(fn).join('\n'),e);
 for(const path of ['map-visibility','map-library'])vm.runInContext(fs.readFileSync('static/js/'+path+'.js','utf8'),e);
 return {e,store,nodes,shown,deleted,messages,layer,center:p=>{center=p;},addKml(name,odjel,lat=1){const k={name,_origName:name,tag:odjel,vis:true,grp:layer(lat,0),_loadedAt:Date.UTC(2026,0,lat)};e.kmlLs.push(k);k.grp.addTo();return k;}};
}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('odjel se sortira numerički, datum opadajuće, blizina prati kartu bez GPS-a',()=>{const h=setup();h.addKml('B','10',2);h.addKml('A','2',1);assert.deepEqual(Array.from(h.e._libraryRows(),r=>r.title),['A','B']);h.e._librarySort('date');assert.equal(h.e._libraryRows()[0].title,'B');h.e._librarySort('proximity');assert.equal(h.e._libraryRows()[0].title,'A');h.center({lat:3,lng:0});assert.equal(h.e._libraryRows()[0].title,'B');});
test('grupna vidljivost poštuje filter i uključuje redove poslije prve stranice',()=>{const h=setup();for(let i=0;i<65;i++)h.addKml('A'+i,'105');const other=h.addKml('Drugi','206');h.e._librarySearch('105');h.e._libraryGroup(false);assert(h.e.kmlLs.slice(0,65).every(k=>!k.vis));assert(other.vis);assert.equal(h.e.kmlLs.length,66);h.e._libraryGroup(true);assert(h.e.kmlLs.every(k=>k.vis));});
test('placeholder server fajla ostaje bez sloja i grupni prikaz ne pokreće mrežu',()=>{const h=setup();h.e.kmlLs.push({_key:'bucket/a.kml',name:'A',vis:false,grp:null});h.e._libraryGroup(true);assert.equal(h.e.kmlLs[0].grp,null);assert.equal(h.e.kmlLs[0].vis,false);});
test('jedna fotografija može se pokazati nakon Sakrij sve bez otkrivanja ostalih',()=>{const h=setup();for(let i=0;i<2;i++)h.e._locFotos.push({ts:i+1,la:i,lo:0,marker:h.layer().addTo()});h.e._tvVisibilitySet('photos',false);const r=h.e._libraryModel()[0];h.e._libraryAction('visibility',r.key);assert(h.shown.has(h.e._locFotos[0].marker));assert(!h.shown.has(h.e._locFotos[1].marker));assert(h.e._tvPhotoVisible(h.e._locFotos[0],false));assert(!h.e._tvPhotoVisible(h.e._locFotos[1],false));h.e.sbUser={id:'B'};assert(h.e._tvPhotoVisible(h.e._locFotos[1],false));h.e.sbUser={id:'A'};assert(!h.e._tvPhotoVisible(h.e._locFotos[1],false));});
test('grupa tragova sakrije i hit-sloj/dužinu bez promjene geometrije',()=>{const h=setup(),t={id:'t',name:'Trag',pts:[[1,2],[3,4]],visible:true};h.e._tragRegistry.push(t);for(const bag of ['_tragLayers','_tragHitLayers','_tragLenMk'])h.e[bag].t=h.layer().addTo();h.e._libraryFilter('tracks');h.e._libraryGroup(false);assert(!t.visible);assert.equal(h.shown.size,0);assert.deepEqual(t.pts,[[1,2],[3,4]]);});
test('nazivi, metapodaci i dataset ključevi ne umeću HTML',()=>{const h=setup();h.addKml('<img onerror=x>','<script>');h.e._libraryRender();const out=h.nodes.get('library-list').innerHTML;assert(!out.includes('<img onerror'));assert(!out.includes('<script>'));assert(out.includes('&lt;img'));});
test('uređivanje KML-a čuva neučitani fajl, brisanje uklanja samo izabrani',async()=>{const h=setup();h.addKml('A','105');h.store.set('local',JSON.stringify({A:{cacheKey:'a'},B:{cacheKey:'b'}}));h.e._kmlSaveTag(0,'106');assert(JSON.parse(h.store.get('local')).B);assert.equal(h.deleted.length,0);await h.e._libraryAction('remove',h.e._libraryModel()[0].key);assert.deepEqual(Object.keys(JSON.parse(h.store.get('local'))),['B']);assert.deepEqual(h.deleted,['a']);});
test('neuspjelo čuvanje registra ne uklanja lokalni sloj',()=>{const h=setup(),k=h.addKml('A','105');h.store.set('local',JSON.stringify({A:{cacheKey:'a'}}));h.e.quota=true;assert.equal(h.e.delK(0),false);assert.equal(h.e.kmlLs.length,1);assert(h.shown.has(k.grp));assert.equal(h.deleted.length,0);});
test('potvrda brisanja ponovo nalazi identitet i odbacuje promjenu naloga',async()=>{const h=setup(),k=h.addKml('A','105');let confirm;h.e._dlgConfirm=()=>new Promise(r=>{confirm=r;});const pending=h.e._libraryAction('remove',h.e._libraryModel()[0].key);h.e.sbUser={id:'B'};confirm(true);await pending;assert(h.e.kmlLs.includes(k));});
test('foto odjel/naziv ostaju po nalogu, bez izmišljanja odjela za stare slike',()=>{const h=setup();h.e._locFotos.push({ts:1,la:0,lo:0,marker:h.layer().addTo()});const r=h.e._libraryModel()[0];assert.equal(r.odjel,'Bez odjela');h.e._libraryEdit(r.key,'odjel','105');h.e._libraryEdit(r.key,'title','Lager');assert.equal(h.e._libraryModel()[0].odjel,'105');assert.equal(h.e._libraryModel()[0].title,'Lager');h.e.sbUser={id:'B'};assert.equal(h.e._libraryModel()[0].odjel,'Bez odjela');});
test('filter, pretraga i sortiranje se vraćaju poslije nove sesije po nalogu',()=>{const first=setup();first.addKml('Odjel 105','105');first.e._libraryFilter('local');first.e._librarySearch('105');first.e._librarySort('date');const next=setup(first.store);next.addKml('Odjel 105','105');next.addKml('Drugi','206');next.e._libraryRender();assert.equal(next.nodes.get('library-search').value,'105');assert.equal(next.nodes.get('library-sort').value,'date');assert.equal(next.e._libraryRows().length,1);next.e.sbUser={id:'B'};next.e._libraryRender();assert.equal(next.nodes.get('library-search').value,'');assert.equal(next.nodes.get('library-sort').value,'department');});
(async()=>{let failed=0;for(const[n,f]of tests)try{await f();console.log('OK '+n);}catch(e){failed++;console.error(n,e);}console.log((tests.length-failed)+'/'+tests.length);if(failed)process.exitCode=1;})();
