'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8'),shapefile=require('../../static/libs/shapefile.min.js'),proj4=require('../../static/libs/proj4.js');
function fn(n){const start=html.search(new RegExp('(?:async )?function '+n+'\\('));assert.ok(start>=0,n);let d=0;for(let i=html.indexOf('{',start);i<html.length;i++){if(html[i]==='{')d++;if(html[i]==='}'&&--d===0)return html.slice(start,i+1);}throw Error(n);}
function shp(type=1,rings=[[[16,44]]]) {
 const points=rings.flat(),parts=type!==1,body=parts?44+4*rings.length+16*points.length:20,b=Buffer.alloc(108+body);
 b.writeInt32BE(9994,0);b.writeInt32BE(b.length/2,24);b.writeInt32LE(1000,28);b.writeInt32LE(type,32);
 b.writeInt32BE(1,100);b.writeInt32BE(body/2,104);b.writeInt32LE(type,108);
 const box=[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];box.forEach((v,i)=>b.writeDoubleLE(v,36+i*8));
 if(parts){box.forEach((v,i)=>b.writeDoubleLE(v,112+i*8));b.writeInt32LE(rings.length,144);b.writeInt32LE(points.length,148);let n=0;rings.forEach((r,i)=>{b.writeInt32LE(n,152+i*4);n+=r.length;});points.forEach((p,i)=>{b.writeDoubleLE(p[0],152+4*rings.length+i*16);b.writeDoubleLE(p[1],160+4*rings.length+i*16);});}
 else{b.writeDoubleLE(points[0][0],112);b.writeDoubleLE(points[0][1],120);}return b;
}
function dbf(name){const b=Buffer.alloc(147,32);b.fill(0,0,65);b[0]=3;b.writeUInt32LE(1,4);b.writeUInt16LE(65,8);b.writeUInt16LE(81,10);b.write('NAZIV',32);b[43]=67;b[48]=80;b[64]=13;Buffer.from(name,'utf8').copy(b,66);b[146]=26;return b;}
function file(name,data){const b=Buffer.isBuffer(data)?data:Buffer.from(data);return {name,size:b.length,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),text:async()=>b.toString('utf8')};}
function setup(){const store=new Map(),cache=new Map(),els=new Map(),messages=[];let seq=0;
 const e={console,proj4,shapefile,setTimeout,TextDecoder,sbUser:{id:'A'},lastP:{la:44,lo:16},_fotoSnapPos:null,_LOCAL_KML_KEY:'local',_projekti:[{id:'P',odjel:'105',gj:'Test'}],_aktivniProjektId:'P',_glCollapsed:new Set(),KCOLS:['blue'],kmlCI:0,kmlLs:[],
  localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(e.quota)throw Error('QuotaExceeded');store.set(k,v);}},_genUUID:()=> 'id-'+(++seq),_kmlcSave:async(k,v)=>{if(!e.idbFail)cache.set(k,v);},_kmlcGet:async k=>cache.get(k)||null,_kmlcDelete:async k=>cache.delete(k),
  showToast:m=>messages.push(m),rndGraniceModal(){},_rndOznakePanel(){},applyKmlStyle(){},map:{fitBounds(){},removeLayer(){}},document:{getElementById:id=>{if(!els.has(id))els.set(id,{style:{},value:'',innerHTML:'',textContent:'',disabled:false,click(){this.clicks=(this.clicks||0)+1;}});return els.get(id);}},
  DOMParser:class{parseFromString(content){return {querySelector:n=>n==='kml'?{}:null,content};}},pkml:()=>({getLayers:()=>[{}],addTo(){e.added=(e.added||0)+1;},getBounds:()=>({isValid:()=>false})})};
 vm.createContext(e);vm.runInContext(html.match(/proj4.defs\('EPSG:31276', [^\n]+/)[0],e);
 vm.runInContext(['_firstCoord','_localKmlSaveContent','_localKmlSaveAll','_localKmlRestore','startLocPhoto','_escHtml','fmtL','_guideRenderRoutes'].map(fn).join('\n'),e);
 vm.runInContext(fs.readFileSync('static/js/local-layer-import.js','utf8'),e);return {e,store,cache,els,messages};}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('stvarni SHP i UTF-8 DBF daju KML sa tačkom, nazivom i sigurnim atributima',async()=>{const h=setup();const r=await h.e._layerReadShp([file('ODJELI.SHP',shp()),file('odjeli.DBF',dbf('Čuvar & <Odjel>')),file('odjeli.cpg','65001'),file('odjeli.shx','')]);assert.equal(r[0].count,1);assert.ok(r[0].content.includes('Čuvar &amp; &lt;Odjel&gt;'));assert.ok(r[0].content.includes('16,44'));assert.ok(r[0].content.includes('<Data name="NAZIV">'));});
test('stvarni SHP poligon čuva unutrašnju rupu u konverziji',async()=>{const h=setup(),outer=[[16,44],[16,44.01],[16.01,44.01],[16.01,44],[16,44]],inner=[[16.002,44.002],[16.008,44.002],[16.008,44.008],[16.002,44.008],[16.002,44.002]];const [r]=await h.e._layerReadShp([file('granica.shp',shp(5,[outer,inner]))]);assert.ok(r.content.includes('<outerBoundaryIs>'));assert.ok(r.content.includes('<innerBoundaryIs>'));});
test('stvarni SHP linija sa MGI koordinatama pravilno se konvertuje za kartu',async()=>{const h=setup();const [r]=await h.e._layerReadShp([file('put.shp',shp(3,[[[6500000,4980000],[6500050,4980050]]]))],'EPSG:31276');const xy=r.content.match(/<coordinates>([^<]+)/)[1].split(' ')[0].split(',').map(Number);assert.ok(Math.abs(xy[0]-18)<.01);assert.ok(xy[1]>44&&xy[1]<46);});
test('PRJ projekcija WGS84/UTM se primjenjuje iako tekst sadrži WGS84',async()=>{const h=setup();const prj='PROJCS["WGS_1984_UTM_Zone_34N",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000],PARAMETER["False_Northing",0],PARAMETER["Central_Meridian",21],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0],UNIT["Meter",1]]';const [r]=await h.e._layerReadShp([file('utm.shp',shp(1,[[[500000,5000000]]])),file('utm.prj',prj)]);const xy=r.content.match(/<coordinates>([^<]+)/)[1].split(',').map(Number);assert.ok(Math.abs(xy[0]-21)<.001);assert.ok(Math.abs(xy[1]-45.153477)<.001);});
test('nepoznata ili odsutna PRJ za metre traži izbor, ne stavlja sloj na pogrešno mjesto',async()=>{const h=setup();await assert.rejects(h.e._layerReadShp([file('x.shp',shp(1,[[[6500000,4980000]]]))]),/prj/);await assert.rejects(h.e._layerReadShp([file('x.shp',shp()),file('x.prj','nepoznato')]),/nije prepoznata/);});
test('neispravan SHP, dupli nazivi i sami prateći fajlovi se odbijaju',async()=>{const h=setup();await assert.rejects(h.e._layerReadShp([file('x.shp','pokvaren')]));await assert.rejects(h.e._layerReadShp([file('x.shp',shp()),file('X.SHP',shp())]),/isti naziv/);await assert.rejects(h.e._layerReadShp([file('x.dbf',dbf('test'))]),/Izaberi .shp/);});
test('veliki lokalni sadržaj ide u IDB, mali registar i backup čuvaju cijeli sloj',async()=>{const h=setup(),content='<kml>'+'x'.repeat(500000)+'</kml>';await h.e._localLayerKml('odjeli.kml',content);assert.equal(h.e.added,1);const data=JSON.parse(h.store.get('local'))['odjeli.kml'];assert.ok(data.cacheKey);assert.equal(data.content,undefined);assert.equal(h.cache.get(data.cacheKey),content);const backup=await h.e._localLayerSnapshot();assert.equal(backup['odjeli.kml'].content,content);assert.equal(backup['odjeli.kml'].cacheKey,undefined);});
test('potvrda IDB-a i registar moraju uspjeti prije dodavanja sloja na kartu',async()=>{for(const flag of ['idbFail','quota']){const h=setup();h.e[flag]=true;await assert.rejects(h.e._localLayerKml('x.kml','<kml/>'),/trajno/);assert.equal(h.e.added,undefined);assert.equal(h.e.kmlLs.length,0);assert.equal(h.cache.size,0);}});
test('dva istovremena uvoza istog naziva čuvaju oba sadržaja',async()=>{const h=setup();await Promise.all([h.e._localLayerKml('x.kml','<kml>1</kml>'),h.e._localLayerKml('x.kml','<kml>2</kml>')]);assert.equal(h.e.kmlLs.length,2);assert.equal(h.e.kmlLs[1].name,'x (2).kml');const b=await h.e._localLayerSnapshot();assert.equal(b['x.kml'].content,'<kml>1</kml>');assert.equal(b['x (2).kml'].content,'<kml>2</kml>');});
test('offline obnova čita stari inline KML i novi IDB sadržaj bez dupliranja',async()=>{const h=setup();h.store.set('local',JSON.stringify({old:{content:'<kml>old</kml>'},new:{cacheKey:'ref'}}));h.cache.set('ref','<kml>new</kml>');await Promise.all([h.e._localKmlRestore(),h.e._localKmlRestore()]);assert.equal(h.e.kmlLs.length,2);});
test('brisanje metadata ne briše IDB sadržaj ako upis registra nije uspio',()=>{const h=setup();h.store.set('local',JSON.stringify({x:{cacheKey:'ref'}}));h.cache.set('ref','data');h.e.quota=true;h.e._localKmlSaveAll();assert.equal(h.cache.get('ref'),'data');h.e.quota=false;h.e._localKmlSaveAll();assert.equal(h.cache.has('ref'),false);});
test('promjena naloga tokom IDB upisa prekida prikaz i uklanja novi sadržaj',async()=>{const h=setup();h.e._kmlcSave=async(k,v)=>{h.cache.set(k,v);h.e.sbUser={id:'B'};};await assert.rejects(h.e._localLayerKml('x.kml','<kml/>'));assert.equal(h.e.added,undefined);assert.equal(h.store.has('local'),false);assert.equal(h.cache.size,0);});
test('obnova backupa pravi IDB kopiju, a postojeći stilovi ostaju sačuvani',async()=>{const h=setup();const d=await h.e._localLayerBackupValue('x',{content:'<kml/>',col:'red',vis:false},'A');assert.equal(h.cache.get(d.cacheKey),'<kml/>');assert.equal(d.content,undefined);assert.equal(d.col,'red');assert.equal(d.vis,false);});
test('Uslikaj direktno otvara samo kameru i hvata GPS poziciju prije snimanja',()=>{const h=setup();h.e.startLocPhoto();const input=h.els.get('loc-photo-cam');assert.equal(input.clicks,1);assert.equal(input.value,'');h.e.lastP.la=45;assert.equal(h.e._fotoSnapPos.la,44);assert.equal(h.e._fotoSnapPos.odjel,'105');h.e._aktivniProjektId='Q';assert.equal(h.e._fotoSnapPos.odjel,'105');h.e.lastP=null;h.e.startLocPhoto();assert.equal(input.clicks,1);assert.ok(!html.includes('id="loc-photo-gal"'));const java=fs.readFileSync('android/app/src/main/java/ba/spd/uss/vlake/MainActivity.java','utf8');assert.ok(!java.includes('launchFallbackPicker'));assert.ok(java.includes('MediaStore.ACTION_IMAGE_CAPTURE'));assert.ok(java.includes('Intent.EXTRA_ALLOW_MULTIPLE'));});
test('sačuvane rute se filtriraju bez brisanja i escapiraju nazive/ID',()=>{const h=setup();h.e._guideRoutesLoad=()=>[{id:'x" onclick="alert(1)',name:'Šumarija <img src=x>',distM:1200,durS:300,osrm:true},{id:'B',name:'Drugi odjel',distM:2000}];h.e.document.getElementById('guide-routes-search').value='Šumarija';h.e._guideRenderRoutes();const s=h.els.get('guide-routes-list').innerHTML;assert.ok(s.includes('&lt;img'));assert.ok(!s.includes('<img'));assert.ok(s.includes('data-id="x&quot;'));assert.equal(h.els.get('guide-routes-count').textContent,'1 / 2');});
(async()=>{let fail=0;for(const[n,f]of tests){try{await f();console.log('OK '+n);}catch(e){fail++;console.error(n+'\n'+e.stack);}}console.log(`${tests.length-fail}/${tests.length}`);if(fail)process.exitCode=1;})();
