'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('index.html','utf8'),section=source.slice(source.indexOf('// Boje i stil prikaza po projektu'),source.indexOf('function buildC()',source.indexOf('// Boje i stil prikaza po projektu')));
function setup(){const store=new Map(),notes=[],nodes=new Map(),layer=()=>({options:{},setStyle(s){Object.assign(this.options,s);}});
 const e={console,sbUser:{id:'A'},_aktivniProjektId:'P',_projekti:[{id:'P',gj:'Una',odjel:'105'},{id:'Q',odjel:'206'}],vlake:[],kolegeVlakeMap:{},localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(e.quota)throw Error('Quota');store.set(k,v);}},document:{getElementById:id=>nodes.get(id)||null,querySelectorAll:()=>[]},map:{removeLayer(){},getZoom:()=>15},showToast:m=>notes.push(m),getIme:()=> 'Emina Projektant',_escHtml:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),fmtL:n=>n+' m',calcL:p=>p.length*100};vm.createContext(e);vm.runInContext(section,e);return{e,store,notes,nodes,layer};}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('postojeće vlastite i kolegine glavne/kraci odmah dobijaju zadanu boju, bez promjene podataka',()=>{const h=setup();h.e.vlake.push({nm:'T1',kr:0,color:'#111111',projektId:'P',poly:h.layer(),pts:[1,2]},{nm:'T1.1',kr:1,color:'#222222',projektId:'P',poly:h.layer(),pts:[1,2]});h.e.kolegeVlakeMap={'B::T2':{nm:'T2',kr:0,color:'#333333',projektId:'P',poly:h.layer()},'B::T2.1':{nm:'T2.1',kr:1,color:'#444444',projektId:'P',poly:h.layer()}};h.e._bojaVlChange('#00aa00');h.e._bojaKrChange('#ee0000');assert.equal(h.e.vlake[0].poly.options.color,'#00aa00');assert.equal(h.e.vlake[1].poly.options.color,'#ee0000');assert.equal(h.e.kolegeVlakeMap['B::T2'].poly.options.color,'#00aa00');assert.equal(h.e.kolegeVlakeMap['B::T2.1'].poly.options.color,'#ee0000');assert.equal(h.e.vlake[0].color,'#111111');assert.deepEqual(h.e.vlake[0].pts,[1,2]);assert.equal(h.e.kolegeVlakeMap['B::T2'].color,'#333333');});
test('stil je odvojen po projektu i nalogu, preživljava ponovno učitavanje',()=>{const h=setup(),v={nm:'T1',kr:0,color:'#111111',projektId:'Q',poly:h.layer()};h.e.vlake.push(v);h.e._bojaVlChange('#123456');assert.equal(v.poly.options.color,'#111111');h.e._aktivniProjektId='Q';h.e._bojaVlChange('#654321');assert.equal(v.poly.options.color,'#654321');h.e._aktivniProjektId='P';assert.equal(h.e.getBojaVlake(),'#123456');h.e.sbUser={id:'B'};assert.equal(h.e.getBojaVlake(),'#60a5fa');h.e.sbUser={id:'A'};assert.equal(h.e.getBojaVlake(),'#123456');h.e._aktivniProjektId='Q';assert.equal(h.e.getBojaVlake(),'#654321');});
test('nova server/realtime polilinija koristi preferencije bez promjene izvorne boje',()=>{const h=setup();h.e._bojaKrChange('#345678');const v={nm:'T10.2',kr:2,color:'#abcdef',projektId:'P',poly:h.layer()};h.e.kolegeVlakeMap['B::T10.2']=v;h.e._vlakaStilApply();assert.equal(v.poly.options.color,'#345678');assert.equal(v.color,'#abcdef');h.e._bojaWChange(7);h.e._bojaDashChange('dot');assert.equal(v.poly.options.weight,7);assert.equal(v.poly.options.lineCap,'round');assert.equal(Number(v.poly.options.dashArray.split(' ')[0]),.01);assert(Number(v.poly.options.dashArray.split(' ')[1])>7);});
test('greška memorije i odsustvo aktivnog projekta ne mijenjaju sačuvane postavke',()=>{const h=setup();h.e._bojaVlChange('#123456');h.e.quota=true;h.e._bojaVlChange('#abcdef');assert.equal(h.e.getBojaVlake(),'#123456');assert(h.notes.length);h.e.quota=false;h.e._aktivniProjektId=null;const n=h.store.size;h.e._bojaVlChange('#abcdef');assert.equal(h.store.size,n);});
test('spisak numerički sortira zajedničke vlake/krake i čuva ista imena različitih projektanata',()=>{const h=setup();h.e.vlake.push({nm:'T10',kr:0,sbId:'a',projektId:'P',pts:[1,2]},{nm:'T2',sbId:'b',projektId:'P',pts:[1,2]},{nm:'T1.10',projektId:'P',pts:[1,2]},{nm:'T1.2',projektId:'P',pts:[1,2]},{nm:'T0',projektId:'Q',pts:[1,2]});h.e.kolegeVlakeMap={'B::T2':{nm:'T2',projektId:'P',ime:'Amir Kolega',pts:[1,2]},'A::T10':{nm:'T10',projektId:'P',ime:'Emina',pts:[1,2]},'B::T0':{nm:'T0',projektId:'Q',pts:[1,2]}};const rows=h.e._projektVlakeRows();assert.deepEqual(Array.from(rows,r=>r.nm),['T1.2','T1.10','T2','T2','T10']);assert.equal(rows.find(r=>r.korisnik_id==='B').ime,'Amir Kolega');assert.equal(rows.filter(r=>r.nm==='T10').length,1);});
test('prikaz s više od 40 vlaka ne gubi ostale, escapira naziv i projektanta',()=>{const h=setup();for(const id of ['project-vlake-list','project-vlake-more','project-vlake-count'])h.nodes.set(id,{innerHTML:'',textContent:'',hidden:false});for(let i=1;i<=65;i++)h.e.vlake.push({nm:'T'+i,projektId:'P',pts:[],projektantIme:'<img src=x>'});h.e._projektVlakeRender();assert.equal((h.nodes.get('project-vlake-list').innerHTML.match(/class="project-vl-row"/g)||[]).length,40);assert(!h.nodes.get('project-vlake-list').innerHTML.includes('<img'));assert(!h.nodes.get('project-vlake-more').hidden);h.e._projektVlakeMore();assert.equal((h.nodes.get('project-vlake-list').innerHTML.match(/class="project-vl-row"/g)||[]).length,65);assert(h.nodes.get('project-vlake-more').hidden);});
test('server kopija i realtime red po istom autoru/nazivu daju jedan aktuelni red',()=>{const h=setup();h.e._serverProjektModel=()=>({rows:[{korisnik_id:'B',nm:'T1',id:'x',pts:[1],ime:'Staro',projekt_id:'P'}]});h.e.kolegeVlakeMap['B::T1']={nm:'T1',sbId:'x',projektId:'P',pts:[1,2,3],ime:'Amir Kolega'};const r=h.e._projektVlakeRows();assert.equal(r.length,1);assert.equal(r[0].pts.length,3);assert.equal(r[0].ime,'Amir Kolega');});
(async()=>{let failed=0;for(const[n,f]of tests)try{await f();console.log('OK '+n);}catch(e){failed++;console.error(n,e);}console.log((tests.length-failed)+'/'+tests.length);if(failed)process.exitCode=1;})();
