'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('index.html','utf8');
function fn(name){const m=src.match(new RegExp('(?:async )?function '+name+'\\('));assert(m,name);let d=0;for(let i=src.indexOf('{',m.index);i<src.length;i++){d+=src[i]==='{';d-=src[i]==='}';if(!d)return src.slice(m.index,i+1);}throw Error(name);}
const tests=[];const test=(n,f)=>tests.push([n,f]);
function env(names,extra={}){const e={console,sbUser:{id:'A'},...extra};vm.createContext(e);vm.runInContext(names.map(fn).join('\n'),e);return e;}
test('Preuzimanje svih 201 redova kada server ograniči stranicu na 40',async()=>{const e=env(['_vlakePreuzmiStranice']);const rows=Array.from({length:201},(_,id)=>({id})),offsets=[];const got=await e._vlakePreuzmiStranice(()=>({order(){return this;},range(a){offsets.push(a);return {data:rows.slice(a,a+40)};}}),'A');assert.equal(got.length,201);assert.deepEqual(offsets,[0,40,80,120,160,200,201]);});
test('Druga stranica pada: nema djelimičnog uspjeha',async()=>{const e=env(['_vlakePreuzmiStranice']);await assert.rejects(e._vlakePreuzmiStranice(()=>({order(){return this;},range(a){return a?{error:Error('offline')}:{data:[{id:1}]};}}),'A'),/offline/);});
test('Odgovor prethodnog naloga ne završava preuzimanje',async()=>{const e=env(['_vlakePreuzmiStranice']);await assert.rejects(e._vlakePreuzmiStranice(()=>({order(){return this;},range(){e.sbUser={id:'B'};return {data:[]};}}),'A'),x=>x.code==='OWNER_CHANGED');});
test('Doznaka: promjena naloga tokom dohvata imena ne dira prikaz ni keš',async()=>{let saves=0;const old=[{user_id:'old'}];const e=env(['dozLoadLayers'],{_dozLoadGen:0,_dozMembers:old,_dozMarkings:old,_dozTracks:old,_dozLoadCachedLayers:()=>null,_dozReadList:async()=>({data:[{user_id:'A'}]}),_dozUcitajTacke:async()=>({data:[]}),_dozCacheLayers(){saves++;},_dozPrimijeniRed:x=>x,dozRenderMapLayers(){throw Error('Ne smije render');},sb:{from(){return {select(){return this;},eq(){return this;},in(){e.sbUser={id:'B'};return {data:[]};}};}}});assert.equal(await e.dozLoadLayers('P'),false);assert.equal(e._dozMembers,old);assert.equal(e._dozMarkings,old);assert.equal(saves,0);});
function parentEnv(){const elements=new Map(),saved=[];const v=[{nm:'T1',projektId:'P',pts:[1,2,3]},{nm:'T1D',projektId:'P',pts:[4,5],junctionOnParent:1},{nm:'T1DD',projektId:'P',pts:[6,7],junctionOnParent:1}];const e=env(['vratiSeNaRoditelja','_pauziOtvoriProzor','_uPauziIntervalu'],{vlake:v,actI:2,_recParentIdx:1,recOn:true,recPaused:false,_recPauseWin:[],_vlakaSaveTimers:{},_parentReturnIdx:null,_parentReturnTrimToIdx:-1,_recSegStart:0,_recSesijaMs:0,_dayActiveMs:0,_dayWorkEnd:null,_precizActive:false,_lastPtAcceptedAt:1,_lastRecTime:1,clearTimeout(){},updateVlakaLabel(){},sbFlushVlaka:i=>saved.push(i),_parentOf:v=>v===e.vlake[1]?0:-1,_kfReset(){},selI(){},_saveDayTiming(){},todayStr:()=>'',_clearRecPreview(){},_updBanner(){},_updFabVisibility(){},showToast(){},document:{getElementById(id){if(!elements.has(id))elements.set(id,{classList:{add(){}},textContent:''});return elements.get(id);}}});return {e,saved,elements};}
test('Dijete → roditelj: pauza, tačan djed, bez rezanja tačaka tokom povratka',()=>{const {e,saved,elements}=parentEnv();e.vratiSeNaRoditelja();assert.equal(e.actI,1);assert.equal(e._recParentIdx,0);assert.equal(e.recPaused,true);assert.equal(e._recPauseWin.length,1);assert.equal(e._uPauziIntervalu(e._recPauseWin,Date.now()+1000),true);assert.deepEqual(e.vlake.map(v=>v.pts),[[1,2,3],[4,5],[6,7]]);assert.deepEqual(saved,[2]);assert.match(elements.get('rec-stats').textContent,/T1D/);e.vratiSeNaRoditelja();assert.equal(e.actI,0);assert.equal(e._recParentIdx,null);assert.equal(e._recPauseWin.length,1);});
test('Roditelj drugog projekta: nema promjene aktivne vlake',()=>{const {e,saved}=parentEnv();e.vlake[1].projektId='Q';e.vratiSeNaRoditelja();assert.equal(e.actI,2);assert.equal(e.recPaused,false);assert.equal(saved.length,0);});
test('Promjena stila čuva još neučitani lokalni KML registar',()=>{let value=JSON.stringify({loaded:{cacheKey:'a'},pending:{cacheKey:'b'}});const e=env(['saveKmlStyles','_localKmlSaveAll'],{kmlLs:[{name:'loaded',col:'#ffffff'}],_LOCAL_KML_KEY:'local',_KML_USER_STYLES_KEY:'server',localStorage:{getItem:()=>value,setItem(k,v){if(k==='local')value=v;}},_kmlcDelete(){throw Error('Nema brisanja sadržaja');}});e.saveKmlStyles();assert.equal(JSON.parse(value).pending.cacheKey,'b');assert.equal(JSON.parse(value).loaded.col,'#ffffff');});
(async()=>{for(const [name,f]of tests){await f();console.log('✔ '+name);}console.log(tests.length+' prošlo');})().catch(e=>{console.error(e);process.exit(1);});
