'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
function fn(name){const start=html.search(new RegExp('(?:async )?function '+name+'\\('));assert.ok(start>=0,name);let d=0;for(let i=html.indexOf('{',start);i<html.length;i++){if(html[i]==='{')d++;if(html[i]==='}'&&--d===0)return html.slice(start,i+1);}throw Error(name);}
const ids=['server-project-select','server-identity','server-project-view','server-project-summary','server-project-authors','server-project-search','server-project-list','server-project-pager','server-project-print','server-project-map','server-project-refresh','data-server-tabs','data-server-received','syncq-list','data-server-pager','data-server-empty'];
const pts=[{la:44,lo:16},{la:44.001,lo:16}];
const row=(nm,uid='other',id=nm)=>({nm,korisnik_id:uid,projekt_id:'P',id,pts,projektant_ime:uid==='other'?'Amir Kolega':'Emina Projektant'});
function setup(){const elements=new Map(ids.map(id=>[id,{innerHTML:'',textContent:'',value:'',style:{},scrollIntoView(){}}])),store=new Map(),queue=[],cache=[],serverRows=[],reports=[],calls=[];
const e={console,sbUser:{id:'me'},sbProfile:{ime:'Emina',prezime:'Projektant'},_projekti:[{id:'P',gj:'GJ Test',odjel:'105',korisnik_id:'me',clanovi:[{korisnik_id:'other'}]},{id:'Q',gj:'Drugi GJ',odjel:'206',korisnik_id:'other',clanovi:[{korisnik_id:'me'}]},{id:'foreign',korisnik_id:'foreign',clanovi:[]}],_aktivniProjektId:'P',vlake:[],_vlakaSaveTimers:{},_dozOdjeli:[],kolegeMap:{other:{ime:'Amir Kolega'}},
 localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},
 document:{getElementById:id=>elements.get(id)||null},window:null,
 _OL:{VLAKE:'cache',load:()=>serverRows,loadQueue:()=>queue},_kvcLoad:id=>cache.filter(r=>r.projekt_id===id),
 _escHtml:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'),
 _SERVER_SAMO_LOKALNO:new Set(['upsert_trag','upsert_log','upsert_labels','delete_trag']),_serverPrimljenoBusy:false,_serverSaljem:false,
 isAdmin:()=>false,isVodeci:()=>false,_openOrDownloadReport:(html,name)=>reports.push({html,name}),
 closeSyncQueuePanel(){},aktivirajProjekt:async id=>calls.push(id),switchTab(){},serverPosalji(){},_fmtAgo:()=> 'maloprije',
 _serverPrimljenoUcitaj:()=>e.received||[],_vlTrazi:'',_vlSort:'naziv',_vlSamoStrme:false,_activeTab:'karta',
 _dozSelId:null,_dozLinkedProjektId:null,
 serverPreuzmiDijeljeno:async id=>calls.push(id),openSyncQueuePanel:()=>e._tabServerPrepare(queue)};
e.window=e;vm.createContext(e);vm.runInContext([fn('dst'),fn('calcL')].join('\n'),e);vm.runInContext(fs.readFileSync('static/js/tab-data.js','utf8'),e);vm.runInContext(fs.readFileSync('static/js/server-panel.js','utf8'),e);
return{e,elements,store,queue,cache,serverRows,reports,calls};}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('projekat objedinjuje vlastite i kolegine vlake, imena i dužine',()=>{const h=setup();h.cache.push(row('T1'));h.e.vlake.push({nm:'T2',sbId:'mine',projektId:'P',pts,projektantIme:'Emina Projektant'});const m=h.e._serverProjektModel();assert.equal(m.rows.length,2);assert.ok(m.total>222&&m.total<224);assert.deepEqual(Array.from(m.rows,r=>r.ime),['Amir Kolega','Emina Projektant']);});
test('iste oznake dva projektanta su dvije vlake',()=>{const h=setup();h.cache.push(row('T1','other','a'),row('T1','me','b'));assert.equal(h.e._serverProjektModel().rows.length,2);});
test('dupla serverska/lokalna kopija ima jedan red, živ snimak pobjeđuje stariji queue',()=>{const h=setup();h.cache.push(row('T1','me','a'));h.serverRows.push(row('T1','me','a'));h.queue.push({type:'upsert_vlaka',payload:row('T1','me','a')});h.e.vlake.push({nm:'T1',sbId:'a',projektId:'P',pts:[...pts,{la:44.002,lo:16}]});const m=h.e._serverProjektModel();assert.equal(m.rows.length,1);assert.equal(m.rows[0].pts.length,3);assert.equal(m.rows[0].pending,true);});
test('zbir ne spaja krajeve međusobno udaljenih vlaka',()=>{const h=setup();h.cache.push(row('T1'),{...row('T2'),pts:[{la:45,lo:17},{la:45.001,lo:17}]});assert.ok(h.e._serverProjektModel().total<225);});
test('neispravna geometrija nije lažna nulta dužina niti spoj preko greške',()=>{const h=setup();h.cache.push({...row('T1'),pts:[pts[0],{la:null,lo:16},pts[1]]});const m=h.e._serverProjektModel();assert.equal(m.rows[0].metres,null);assert.equal(m.incomplete,1);assert.equal(m.total,0);});
test('vlasnik i član vide iste zajedničke serverske podatke',()=>{const h=setup();h.cache.push(row('T1','me'),row('T2'));assert.equal(h.e._serverProjektModel().rows.length,2);h.e.sbUser={id:'other'};assert.equal(h.e._serverProjektModel().rows.length,2);});
test('tuđe neposlane operacije nisu u listi drugog naloga',()=>{const h=setup();h.queue.push({_uid:'other',type:'upsert_vlaka',payload:row('T3')});assert.equal(h.e._serverProjektModel().rows.length,0);});
test('izbor projekta ne mijenja aktivnu kartu, niti otvara nedostupan projekat',()=>{const h=setup();h.e._serverPanelRender();h.e._serverProjektSelect('Q');assert.equal(h.e._serverProjektModel().project.id,'Q');assert.equal(h.e._aktivniProjektId,'P');h.e._serverProjektSelect('foreign');assert.notEqual(h.e._serverProjektModel().project.id,'foreign');});
test('promjena naloga poništava odabrani projekat i metapodatke preuzimanja',()=>{const h=setup();h.e._serverProjektPreuzeto('P',[row('T1')]);h.e.sbUser={id:'foreign'};assert.equal(h.e._serverProjektModel().project.id,'foreign');assert.equal(h.e._serverProjektModel().downloaded,null);});
test('pretraga i stranice ne skraćuju zbir i puni ispis (145 vlaka)',()=>{const h=setup();for(let i=1;i<=145;i++)h.cache.push(row('T'+i));h.e._serverPanelRender();assert.equal((h.elements.get('server-project-list').innerHTML.match(/class="sp-vlaka"/g)||[]).length,60);h.e._serverProjektPage(2);assert.equal((h.elements.get('server-project-list').innerHTML.match(/class="sp-vlaka"/g)||[]).length,25);h.e._serverProjektSearch('T145');h.e._serverProjektReport();assert.equal((h.reports[0].html.match(/<tr><td>/g)||[]).length,145);assert.ok(h.reports[0].html.includes('Amir Kolega'));});
test('preimenovanje po istom ID-ju ne duplicira vlaku',()=>{const h=setup();h.serverRows.push(row('T1','other','a'));h.cache.push(row('T2','other','a'));assert.deepEqual(Array.from(h.e._serverProjektModel().rows,r=>r.nm),['T2']);});
test('lokalna vlaka u debounce-u nije označena kao već poslana',()=>{const h=setup();h.e.vlake.push({nm:'T1',sbId:'a',projektId:'P',pts});h.e._vlakaSaveTimers[0]=1;assert.equal(h.e._serverProjektModel().rows[0].pending,true);});
test('kopija koja nedostaje u zadnjem preuzimanju ostaje i ima jasno označen status',()=>{const h=setup();h.cache.push(row('T1'));h.e._serverProjektPreuzeto('P',[]);assert.equal(h.e._serverProjektModel().rows[0].stale,true);});
test('novi realtime ID dopunjava pregled bez lažne oznake zastarjele kopije',()=>{const h=setup();h.e._serverProjektPreuzeto('P',[]);h.cache.push(row('T2'));h.e._serverProjektDopuni('P',[row('T2')]);assert.equal(h.e._serverProjektModel().rows[0].stale,false);});
test('Primljeno broji i projekte vlasnika, lokalne operacije se ne broje kao slanje',()=>{const h=setup();h.e.received=[{projektId:'P'},{projektId:'Q'}];h.queue.push({type:'upsert_trag',_uid:'me'}, {type:'delete_vlaka',_uid:'me'});h.e._tabServerCounts();assert.match(h.elements.get('data-server-tabs').innerHTML,/Primljeno \(2\)/);assert.match(h.elements.get('data-server-tabs').innerHTML,/Za slanje \(1\)/);});
test('novi tab projekta je vidljiv, primljeno i queue su odvojeni',()=>{const h=setup();h.e._tabServerPrepare([]);assert.equal(h.elements.get('server-project-view').hidden,false);assert.equal(h.elements.get('syncq-list').hidden,true);h.e._tabServer('received');assert.equal(h.elements.get('server-project-view').hidden,true);assert.equal(h.elements.get('data-server-received').hidden,false);});
test('HTML nazivi projekta/projektanta i ispis su escapirani',()=>{const h=setup();h.e._projekti[0].gj='<img src=x onerror=alert(1)>';h.cache.push({...row('<script>'),projektant_ime:'<svg onload=x>'});h.e._serverPanelRender();h.e._serverProjektReport();assert.ok(!h.elements.get('server-project-list').innerHTML.includes('<svg'));assert.ok(!h.reports[0].html.includes('<img'));assert.ok(h.reports[0].html.includes('&lt;svg'));});
test('refresh čita tačno odabrani projekat, bez mijenjanja karte',async()=>{const h=setup();h.e._serverPanelRender();h.e._serverProjektSelect('Q');await h.e._serverProjektRefresh();assert.deepEqual(h.calls,['Q']);assert.equal(h.e._aktivniProjektId,'P');});
test('preuzimanje vlastitih vlaka čuva žive neposlane izmjene i snimanje',()=>{const h=setup();const applied=[];h.e._applyVlakeRows=r=>applied.push(...r);h.e.vlake.push({nm:'T1',sbId:'a',projektId:'P',pts:[...pts,{la:44.002,lo:16}]});h.e._vlakaSaveTimers[0]=1;vm.runInContext(fn('_serverPrimijeniMojeVlake'),h.e);h.e._serverPrimijeniMojeVlake([row('T1','me','a'),row('T2','me','b')],'me');assert.deepEqual(applied.map(r=>r.nm),['T2']);assert.equal(h.e.vlake[0].pts.length,3);delete h.e._vlakaSaveTimers[0];h.e.recOn=true;h.e.actI=0;h.e._serverPrimijeniMojeVlake([row('T1','me','a')],'me');assert.equal(applied.length,1);});
test('keš preimenovane vlake čuva ID, projektanta, reviziju i samo novi naziv',()=>{const h=setup();h.e._KVC_KEY='kvc';h.e._serverPrimljenoZapamti=()=>{};vm.runInContext(fn('_kvcSave'),h.e);h.e._kvcSave('P',[row('T1','other','a')]);h.e._kvcSave('P',[{...row('T2','other','a'),rev:7}]);const cached=JSON.parse(h.store.get('kvc')).P;assert.deepEqual(Object.keys(cached),['other::T2']);assert.equal(cached['other::T2'].ime,'Amir Kolega');assert.equal(cached['other::T2'].rev,7);});
test('zbir po projektantima čuva različite naloge sa istim imenom',()=>{const h=setup();h.cache.push({...row('T1','other','a'),projektant_ime:'Isto ime'},{...row('T2','me','b'),projektant_ime:'Isto ime'});const m=h.e._serverProjektModel();assert.equal(m.authors.length,2);assert.equal(m.authors.reduce((n,a)=>n+a.total,0),m.total);assert.equal(m.authors[0].count,1);});
test('filter projektanta koristi nalog, ispis i zbir ostaju cijeli projekat',()=>{const h=setup();h.cache.push(row('T1'),row('T2','me','b'));h.e._serverProjektAuthor('other');const list=h.elements.get('server-project-list').innerHTML;assert.ok(list.includes('T1'));assert.ok(!list.includes('T2'));h.e._serverProjektReport();assert.ok(h.reports[0].html.includes('T2'));assert.ok(h.reports[0].html.includes('Pregled po projektantima'));h.e._serverProjektSelect('P');assert.ok(h.elements.get('server-project-list').innerHTML.includes('T2'));});
test('oštećen ali validan JSON metapodataka ne ruši Server',()=>{const h=setup();h.cache.push(row('T1'));h.store.set('tvlake_server_project_v1_me_P',JSON.stringify({ts:10,ids:{bad:true}}));h.e._serverPanelRender();assert.equal(h.e._serverProjektModel().downloaded,null);h.e._serverProjektDopuni('P',[row('T2')]);assert.ok(h.elements.get('server-project-list').innerHTML.includes('T1'));});
(async()=>{let failed=0;for(const[n,f]of tests){try{await f();console.log('OK '+n);}catch(e){failed++;console.error('FAIL '+n+'\n'+e.stack);}}console.log(`${tests.length-failed}/${tests.length}`);if(failed)process.exitCode=1;})();
