'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('static/js/spd-profile.js','utf8');
function setup(){
 const nodes=new Map(),calls=[],events={};
 const node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,textContent:'',dataset:{},setAttribute(k,v){this[k]=v;},focus(){e.document.activeElement=this;},getClientRects:()=>[1],isConnected:true,querySelectorAll:()=>[]});return nodes.get(id);};
 const e={Date,console,sbUser:{id:'A'},sbProfile:{id:'A',ime:'Amir',prezime:'Šumar',sumarija:'ŠPD US ŠUME',odobren:true},isSpdField:()=>!e.sbProfile?.is_admin&&e.sbProfile?.sumarija==='ŠPD US ŠUME',document:{documentElement:{dataset:{fieldTheme:'dark'}},getElementById:node,addEventListener:(k,v)=>events[k]=v},addEventListener:()=>{},navigator:{onLine:false},APP_VER:'v2.4.6',_tacke:[{},{}],_tragRegistry:[{}],_msrRegistry:[],_locFotos:[{}],_trnSharedLoad:()=>[{}],_activeLayerKey:()=> '_sqlite_0',_sqlLayers:[{name:'Karta Una',saved:false}],gpsOn:true,lastP:{ac:null},_lastGpsFixTime:Date.now(),_isOfflineMode:true,_netKvalitet:()=> 'dobra',_serverNaCekanju:()=>({stavki:3}),_shareLiveOn:false,_tragOn:true,_tragPaused:true,
 closeMenuDropdown:()=>{},showToast:s=>calls.push('toast'),switchTab:t=>calls.push(t),terenSetTab:t=>calls.push(t),TerenWorkspace:{search:q=>calls.push('search:'+q),jump:id=>calls.push(id)},openOznakePanel:()=>calls.push('photos'),_librarySearch:q=>calls.push('photoSearch:'+q),_libraryFilter:c=>calls.push(c),_openLayerSheet:()=>calls.push('maps'),_lsTab:t=>calls.push(t),_exportFieldRecovery:async()=>calls.push('backup'),promijeniPin:()=>calls.push('pin'),azurirajAplikaciju:()=>calls.push('update'),openSyncQueuePanel:()=>calls.push('queue'),toggleFieldTheme:()=>{e.document.documentElement.dataset.fieldTheme='day';}};
 e.window=e;vm.createContext(e);vm.runInContext(fs.readFileSync('static/js/access-policy.js','utf8'),e);vm.runInContext(source,e);return {e,nodes,calls,events};
}
const h=setup(),a=h.e.SpdProfile;a.open();assert.equal(h.nodes.get('wrapper').inert,true);assert.equal(h.nodes.get('spd-points').textContent,'2');assert.equal(h.nodes.get('spd-network').textContent,'Bez interneta');assert.match(h.nodes.get('spd-map-note').textContent,/spremanje kopije još traje/);assert.equal(h.nodes.get('spd-gps').textContent,'Aktivan · tačnost nepoznata');assert.equal(h.nodes.get('spd-recording').textContent,'Trag pauziran');
h.e._sqlLayers[0].saved=true;h.e._lastGpsFixTime=Date.now()-60000;a.render();assert.match(h.nodes.get('spd-map-note').textContent,/Kopija sačuvana/);assert.equal(h.nodes.get('spd-gps').textContent,'Pozicija zastarjela');a.action('theme');assert.equal(h.nodes.get('spd-theme')['aria-pressed'],'true');assert.equal(h.nodes.get('spd-profile').hidden,false);
a.action('trag');assert.deepEqual(h.calls,['teren','search:','trag','trn-records']);assert.equal(h.nodes.get('wrapper').inert,false);a.open();a.action('photos');assert.deepEqual(h.calls.slice(-4),['karta','photos','photoSearch:','photos']);
h.e.sbProfile={...h.e.sbProfile,odobren:false,probni_do:new Date(Date.now()+6*86400000).toISOString()};a.open();assert.match(h.nodes.get('spd-access-title').textContent,/Probni pristup/);assert.match(h.nodes.get('spd-access-note').textContent,/Administrator/);
h.e.sbUser={id:'B'};a.action('backup');assert.equal(h.nodes.get('spd-profile').hidden,true);assert.ok(!h.calls.includes('backup'));assert.equal(h.nodes.get('spd-menu-launch').hidden,true);
h.e.sbUser={id:'A'};h.e.sbProfile.is_admin=true;a.sync();a.open();assert.equal(h.nodes.get('spd-profile').hidden,true);h.e.sbProfile.is_admin=false;h.e.sbProfile.probni_do=new Date(Date.now()-1000).toISOString();a.sync();a.open();assert.equal(h.nodes.get('spd-profile').hidden,true);
assert.ok(!/fetch\(|setInterval\(|setTimeout\(|localStorage\.|\.rpc\(/.test(source),'profil pokreće mrežu, timer ili upis');
console.log('ŠPD profil: offline stanje, kopija karte, pregled zapisa, probni pristup, uloge i promjena naloga — OK');
