'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
function fn(n){const m=html.match(new RegExp('(?:async )?function '+n+'\\('));assert.ok(m,n);let d=0;for(let i=html.indexOf('{',m.index);i<html.length;i++){if(html[i]==='{')d++;if(html[i]==='}'&&--d===0)return html.slice(m.index,i+1);}throw Error(n);}
const pts=[{la:44.9,lo:16,al:300},{la:44.903,lo:16,al:340}];
const names=['_escHtml','_esc','dst','calcL','calcElev','fmtL','fmtHa','fmtDate','fmtDateShort','_pmFilterList','_pmMatchProject','_pmListCaption','_pmProjectRows','_pmCardHtml','_pmUserName','_pmRenderList','_pmRenderAdminList','_projektTimIds','_projektIme','_logEntryMatchesProject','_pmOpenDetail','_pmBuildDetail','_vlakeStatsSecsHtml','_pmTime'];
function setup(){const els=new Map(['pm-list','pm-list-inner','pm-list-caption','pm-list-wrap','pm-detail','pm-back-btn','pm-title','pm-body','pm-detail-body'].map(id=>[id,{innerHTML:'',textContent:'',style:{}}])),store=new Map();
const rows=[{id:'a',projekt_id:'P',korisnik_id:'A',nm:'T1',kr:0,pts,projektant_ime:'Emina Projektant'},{id:'b',projekt_id:'P',korisnik_id:'B',nm:'T1',kr:0,pts,projektant_ime:'Amir Kolega'},{id:'c',projekt_id:'Q',korisnik_id:'B',nm:'T2',kr:1,pts,projektant_ime:'Amir Kolega'}];
const e={console,document:{getElementById:id=>els.get(id)},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},sbUser:{id:'A'},sbProfile:{id:'A',ime:'Emina',prezime:'Projektant'},_aktivniProjektId:'P',_projekti:[{id:'P',odjel:'105',gj:'Una',korisnik_id:'A',datum:'2026-10-02',clanovi:[{korisnik_id:'B'}]},{id:'Q',odjel:'201',gj:'Grmeč',korisnik_id:'B',clanovi:[{korisnik_id:'A'}]},{id:'R',odjel:'202',gj:'Una',korisnik_id:'A',clanovi:[]}],vlake:[],dnevniLog:[],kolegeMap:{B:{ime:'Amir Kolega'}},isVodeci:()=>false,isAdmin:()=>false,_pmNadzor:false,_pmAdminRows:null,_pmDozRows:null,_OL:{VLAKE:'vlake',load:()=>rows,loadQueue:()=>[]},_kvcLoad:()=>[],_mrezaProbaj:()=>false,_enrichVlakeElevation:async()=>{}};
e.window=e;vm.createContext(e);vm.runInContext("let _pmSearch='',_pmFilter='all',_pmDetailId=null,_pmLastData=null;"+names.map(fn).join('\n'),e);vm.runInContext(fs.readFileSync('static/js/server-panel.js','utf8'),e);return {e,els,rows};}
const tests=[];const test=(n,f)=>tests.push([n,f]);
test('kartice broje i vlake kolega iz zadnje preuzetog keša',()=>{const h=setup();h.e._pmRenderList();const s=h.els.get('pm-list-inner').innerHTML;assert.equal((s.match(/<button type="button" class="pm-card/g)||[]).length,3);assert.ok(s.includes('Emina Projektant'));assert.ok(s.includes('Amir Kolega'));assert.ok(s.includes('<b>2</b><small>Vlaka</small>'));});
test('pretraga i filteri ne skraćuju globalni sažetak niti mijenjaju aktivni projekat',()=>{const h=setup();h.e._pmRenderList();const all=h.els.get('pm-list').innerHTML;h.e._pmFilterList('Amir','shared');assert.equal(h.els.get('pm-list').innerHTML,all);assert.match(h.els.get('pm-list-caption').textContent,/1 od 3/);assert.equal(h.e._aktivniProjektId,'P');h.e._pmFilterList('nepoznato');assert.ok(h.els.get('pm-list-inner').innerHTML.includes('Nema projekata'));});
test('čitanje projekta za PM ne mijenja odabrani projekat Servera',()=>{const h=setup();h.e._aktivniProjektId='Q';h.e._serverPanelRender();assert.equal(h.e._serverProjektModel().project.id,'Q');h.e._pmProjectRows(h.e._projekti[0]);assert.equal(h.e._serverProjektModel().project.id,'Q');assert.equal(h.e._serverProjektModel('nedostupan').rows.length,0);});
test('nazivi, vlasnik i ID u kartici su sigurno escapirani',()=>{const h=setup();const s=h.e._pmCardHtml({id:'x" onclick="alert(1)',odjel:'<img src=x>',gj:'<svg>'},'<script>',1,0,10);assert.ok(!s.includes('<img'));assert.ok(!s.includes('<svg>'));assert.ok(!s.includes('<script>'));assert.ok(s.includes('data-project="x&quot; onclick=&quot;alert(1)"'));assert.ok(s.includes('_pmOpenDetail(this.dataset.project)'));});
test('admin filter koristi iste kartice i postojeće RPC agregate',()=>{const h=setup();h.e.sbProfile.is_admin=true;h.e._pmNadzor=true;h.e._pmAdminRows=[{...h.e._projekti[0],vlasnik:'Emina Projektant',maticnih:8,krakova:3,ukupno_m:3000},{...h.e._projekti[1],vlasnik:'Amir Kolega',maticnih:4,krakova:2,ukupno_m:2000}];h.e._pmFilterList('Amir');const s=h.els.get('pm-list-inner').innerHTML;assert.equal((s.match(/<button type="button" class="pm-card/g)||[]).length,1);assert.ok(s.includes('<b>4</b>'));assert.ok(s.includes('2.00 km'));});
test('offline detalj ima vidljiv povratak, zajedničku listu i čuva tačke keša tokom obogaćivanja',async()=>{const h=setup();h.e._enrichVlakeElevation=async rows=>{rows[0].pts[0].al=999;};await h.e._pmOpenDetail('P');assert.equal(h.els.get('pm-back-btn').style.display,'inline-flex');assert.equal(h.rows[0].pts[0].al,300);assert.ok(h.els.get('pm-detail-body').innerHTML.includes('2 vlaka i krakova'));assert.ok(h.els.get('pm-detail-body').innerHTML.includes('Amir Kolega'));assert.ok(h.els.get('pm-detail-body').innerHTML.includes('pm-table-scroll'));});
test('detalj bez vlaka ostaje pregledan i ne mijenja dostupne akcije',()=>{const h=setup();const s=h.e._pmBuildDetail(h.e._projekti[2],[],[]);assert.ok(s.includes('Odjel 202'));assert.ok(s.includes('0 vlaka i krakova'));for(const a of ['_pmShowOnMap()','_pmAktiviraj()','_pmExportReport()','_pmNagibAnaliza()'])assert.ok(s.includes(a));});
test('krak dva projektanta sa istom oznakom glavne vlake prikazuje se samo kod svog autora',()=>{const h=setup();const s=h.e._vlakeStatsSecsHtml(42.5,[h.rows[0],h.rows[1],{...h.rows[0],nm:'T1 - krak 1',kr:1}]);assert.equal((s.match(/T1 - krak 1/g)||[]).length,1);assert.ok(s.includes('Amir Kolega'));});
(async()=>{let failed=0;for(const[n,f]of tests){try{await f();console.log('OK '+n);}catch(e){failed++;console.error(n+'\n'+e.stack);}}console.log(`${tests.length-failed}/${tests.length}`);if(failed)process.exitCode=1;})();
