const assert=require('node:assert/strict'),d=require('../../static/js/vlaka-direction.js'),fs=require('node:fs'),vm=require('node:vm');
assert.deepEqual(d.markerPlan(300,'start'),[{f:.5,sign:-1}]);assert.equal(d.markerPlan(301,'end').length,2);assert.deepEqual(d.markerPlan(500,'both'),[]);assert.deepEqual(d.markerPlan(100,'both'),[]);assert.equal(d.markerPlan(100,'off').length,0);
for(const length of [100,500]){const p=d.markerPlan(length,'both',.2);assert.deepEqual(p.map(r=>r.sign),[-1,0,1]);assert.equal(p[1].f,.2);assert(p[0].f<.2&&p[2].f>.2);}
assert.equal(d.markerPlan(100,'end',null,6).length,6);const six=d.markerPlan(500,'both',.8,6);assert.equal(six.filter(p=>p.sign!==0).length,6);assert(six.filter(p=>p.sign<0).every(p=>p.f<.8));assert(six.filter(p=>p.sign>0).every(p=>p.f>.8));assert.deepEqual(d.markerPlan(500,'both',1),[]);assert.deepEqual(d.markerPlan(500,'both',0),[]);
const pts=[{la:45,lo:16},{la:45,lo:16.01}],point={la:45,lo:16.002},chosen=d.routeProjection(pts,point);assert(Math.abs(chosen.f-.2)<.001);assert.equal(chosen.distance,0);const longer=d.routeProjection([...pts,{la:45,lo:16.02}],{...point,atM:chosen.atM},chosen.atM);assert(Math.abs(longer.f-.1)<.001);assert(Math.abs(longer.atM-chosen.atM)<.01);assert.equal(d.routeProjection([{la:NaN,lo:16},pts[1]],point),null);assert.equal(d.routeProjection([pts[0],pts[0]],point),null);
const back=[pts[0],pts[1],pts[0]],last=d.routeProjection(back,pts[0],2000);assert.equal(last.f,1);assert.equal(d.routeProjection(back,pts[0],0).f,0);
assert.deepEqual(d.cleanSettings(null),d.cleanSettings({}));assert.equal(d.cleanSettings({width:NaN,size:900,count:-1,color:'red',visible:'no'}).size,30);assert.equal(d.cleanSettings({color:'#000000',count:6,width:1,size:18,visible:false}).visible,false);
assert.equal(d.chooseEnd(10,150),'start');assert.equal(d.chooseEnd(250,5),'end');assert.equal(d.chooseEnd(300,400),null);assert.equal(d.chooseEnd(Infinity,Infinity),null);assert(d.segmentDistance({la:45,lo:16},[45,15],[45,17])<.001);
const s=fs.readFileSync('index.html','utf8'),code=s.slice(s.indexOf('function _vlakaStroke('),s.indexOf('function getVlakaDashArray(')),c={};vm.createContext(c);vm.runInContext(code,c);
for(const w of [2,4,8])for(const z of [11,13,15,18]){const dash=c._vlakaStroke('dash',w,z);assert.equal(dash.lineCap,'butt');const [ink,gap]=dash.dashArray.split(' ').map(Number);assert(ink>=gap*3);const dot=c._vlakaStroke('dot',w,z);assert.equal(dot.lineCap,'round');assert.equal(Number(dot.dashArray.split(' ')[0]),.01);assert(Number(dot.dashArray.split(' ')[1])>w);}
console.log('OK: designer split at 20%/80%, no legacy midpoint, stable split when route grows/returns, manual counts, settings validation and dash/dot patterns');

assert.equal(d.cleanSettings({placement:'beside'}).placement,'beside');assert.equal(d.cleanSettings({placement:'both'}).placement,'on');assert.equal(d.cleanSettings({}).placement,'on');
